pub mod model;
pub mod parser;
pub mod reader;
pub mod renderer;
pub mod serializer;
mod query;
mod queries;
pub mod builtinpage;
pub mod builder;
pub mod index;
pub mod page_index;
pub mod config;
pub mod favourite;
pub mod media;
pub mod markdown;
pub mod datatypes;