pub mod builder;
pub mod builtinpage;
pub mod data;
pub mod datatypes;
pub mod favourite;
pub mod index;
pub mod kanban;
pub mod media;
pub mod model;
pub mod parser;
pub mod plot;
mod queries;
mod query;
pub mod reader;
pub mod renderer;
pub mod search;
pub mod serializer;
pub mod syntax;
pub mod templates;
