title: Looksyk
description: A simple personal knowledge platform with a focus on clean markdown files, simple queries and a journal.
show_downloads: true
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jemoji
markdown: kramdown
