pub mod block_properties;
pub mod config;
pub mod design;
pub mod favourites;
pub(crate) mod help;
pub mod kanban;
mod link;
pub mod markdown;
pub mod media;
pub mod metainfo;
pub mod page;
mod page_type;
pub mod state;
pub mod r#static;
pub mod plot;
pub mod routes;
