on:
  release:
    types: [published]
name: Release Local Flatpak
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      - name: Build flatpak
        run: |
          flatpak run org.flatpak.Builder --force-clean --user --install --install-deps-from=flathub --ccache --mirror-screenshots-url=https://dl.flathub.org/media/ --repo=repo builddir ./de.sebastianruziczka.looksyk.local.yml
          flatpak build-bundle repo looksyk.flatpak de.sebastianruziczka.looksyk
      - name: Upload looksyk.flatpak
        run: gh release upload "$GITHUB_REF_NAME" looksyk.flatpak --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}