on:
  release:
    types: [published]
name: Release Local Flatpak
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installiere Flatpak und flatpak-builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
      - name: Build flatpak
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          eval "$(dbus-launch --sh-syntax)"
          flatpak install --user -y flathub org.flatpak.Builder
          flatpak run org.flatpak.Builder --force-clean --user --install --install-deps-from=flathub --ccache --mirror-screenshots-url=https://dl.flathub.org/media/ --repo=repo builddir ./de.sebastianruziczka.looksyk.local.yml
          flatpak build-bundle repo looksyk.flatpak de.sebastianruziczka.looksyk
      - name: Upload looksyk.flatpak
        run: gh release upload "$GITHUB_REF_NAME" looksyk.flatpak --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}