name: Scan for security issues

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  backend-scan:
    name: backend cargo scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: | 
          cargo install cargo-audit --locked 
          cargo audit
        working-directory: ./backend

  frontend-scan:
    name: frontend scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and scan
        run: |
          npm i
          npm audit
        working-directory: ./frontend/looksyk
  application-wrapper-scan:
    name: application-wrapper scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and scan
        run: |
          npm i
          npm audit
        working-directory: ./application-wrapper/Looksyk