name: Test Build AppImage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ stable ]
    types: [ opened, synchronize, reopened ]
    base: [ stable ]
    paths-ignore:
      - '**.md'

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install libcurl development files
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - name: Build project
        run: bash build.sh

      - name: Build AppImage
        run: bash build-appimage.sh
